//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\BottomNavigationMenuViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BottomNavigationMenuViewImpl")
#ifdef RESTRICT_BottomNavigationMenuViewImpl
#define INCLUDE_ALL_BottomNavigationMenuViewImpl 0
#else
#define INCLUDE_ALL_BottomNavigationMenuViewImpl 1
#endif
#undef RESTRICT_BottomNavigationMenuViewImpl

#if !defined (ASBottomNavigationMenuViewImpl_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl))
#define ASBottomNavigationMenuViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean;
@class ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder;
@class ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder;
@class ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASBottomNavigationMenuViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean *)getBean;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean *)getParamsBean;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl)

inline NSString *ASBottomNavigationMenuViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationMenuViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationMenuViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASBottomNavigationMenuViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationMenuViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationMenuViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_init(ASBottomNavigationMenuViewImpl *self);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *new_ASBottomNavigationMenuViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *create_ASBottomNavigationMenuViewImpl_init(void);

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_initWithNSString_(ASBottomNavigationMenuViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *new_ASBottomNavigationMenuViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *create_ASBottomNavigationMenuViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_initWithNSString_withNSString_(ASBottomNavigationMenuViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *new_ASBottomNavigationMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl *create_ASBottomNavigationMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl)

@compatibility_alias ComAsheraNavigationviewBottomNavigationMenuViewImpl ASBottomNavigationMenuViewImpl;

#endif

#if !defined (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt))
#define ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt_

#define RESTRICT_BottomNavigationMenuView 1
#define INCLUDE_ADXBottomNavigationMenuView 1
#include "BottomNavigationMenuView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASBottomNavigationMenuViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt : ADXBottomNavigationMenuView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASBottomNavigationMenuViewImpl:(ASBottomNavigationMenuViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt *self, ASBottomNavigationMenuViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt *new_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt *create_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewExt)

#endif

#if !defined (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder))
#define ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASBottomNavigationMenuViewImpl;

@interface ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASBottomNavigationMenuViewImpl:(ASBottomNavigationMenuViewImpl *)outer$;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                          withId:(id)arg1;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)endAnimator;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)invalidate;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)requestLayout;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)reset;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)startAnimator;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetAlpha;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetBackground;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetBackgroundTint;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetBottom;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetClickable;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetClipChildren;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetClipToPadding;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetContentDescription;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetDuplicateParentState;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetEnabled;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetFocusable;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetForeground;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetForegroundGravity;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetForegroundTint;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetForegroundTintMode;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetId;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAlpha;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsFocused;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsHidden;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsOpaque;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosTag;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosTintColor;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetKeepScreenOn;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetLayoutDirection;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetLayoutMode;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetLeft;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetLongClickable;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetMaxHeight;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetMaxWidth;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetMinHeight;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetMinWidth;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelDescPath;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelIdPath;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelParam;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelPojoToUi;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelSyncEvents;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetModelUiToPojo;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingBottom;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingEnd;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingLeft;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingRight;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingStart;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetPaddingTop;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetRight;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetRotation;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetRotationX;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetRotationY;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetScaleX;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetScaleY;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetSelected;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTextAlignment;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTextDirection;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTop;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTransformPivotX;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTransformPivotY;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTranslationX;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTranslationY;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetTranslationZ;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetValidateForm;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)tryGetVisibility;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                                withId:(id)arg1;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *self, ASBottomNavigationMenuViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *new_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder *create_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandBuilder)

#endif

#if !defined (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean))
#define ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASBottomNavigationMenuViewImpl;
@protocol ASIWidget;

@interface ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASBottomNavigationMenuViewImpl:(ASBottomNavigationMenuViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean *self, ASBottomNavigationMenuViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean *new_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean *create_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewBean)

#endif

#if !defined (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean))
#define ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASBottomNavigationMenuViewImpl;

@interface ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASBottomNavigationMenuViewImpl:(ASBottomNavigationMenuViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean *self, ASBottomNavigationMenuViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean *new_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean *create_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewParamsBean)

#endif

#if !defined (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder_) && (INCLUDE_ALL_BottomNavigationMenuViewImpl || defined(INCLUDE_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder))
#define ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASBottomNavigationMenuViewImpl;

@interface ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASBottomNavigationMenuViewImpl:(ASBottomNavigationMenuViewImpl *)outer$;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)reset;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *self, ASBottomNavigationMenuViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *new_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder *create_ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder_initWithASBottomNavigationMenuViewImpl_(ASBottomNavigationMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationMenuViewImpl_BottomNavigationMenuViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_BottomNavigationMenuViewImpl")
