//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\BottomNavigationItemViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BottomNavigationItemViewImpl")
#ifdef RESTRICT_BottomNavigationItemViewImpl
#define INCLUDE_ALL_BottomNavigationItemViewImpl 0
#else
#define INCLUDE_ALL_BottomNavigationItemViewImpl 1
#endif
#undef RESTRICT_BottomNavigationItemViewImpl

#if !defined (ASBottomNavigationItemViewImpl_) && (INCLUDE_ALL_BottomNavigationItemViewImpl || defined(INCLUDE_ASBottomNavigationItemViewImpl))
#define ASBottomNavigationItemViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASBottomNavigationItemViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationItemViewImpl)

inline NSString *ASBottomNavigationItemViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationItemViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationItemViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASBottomNavigationItemViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationItemViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationItemViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASBottomNavigationItemViewImpl_init(ASBottomNavigationItemViewImpl *self);

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *new_ASBottomNavigationItemViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *create_ASBottomNavigationItemViewImpl_init(void);

FOUNDATION_EXPORT void ASBottomNavigationItemViewImpl_initWithNSString_(ASBottomNavigationItemViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *new_ASBottomNavigationItemViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *create_ASBottomNavigationItemViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASBottomNavigationItemViewImpl_initWithNSString_withNSString_(ASBottomNavigationItemViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *new_ASBottomNavigationItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl *create_ASBottomNavigationItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationItemViewImpl)

@compatibility_alias ComAsheraNavigationviewBottomNavigationItemViewImpl ASBottomNavigationItemViewImpl;


#endif

#if !defined (ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt_) && (INCLUDE_ALL_BottomNavigationItemViewImpl || defined(INCLUDE_ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt))
#define ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt_

#define RESTRICT_BottomNavigationItemView 1
#define INCLUDE_ADXBottomNavigationItemView 1
#include "BottomNavigationItemView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASBottomNavigationItemViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt : ADXBottomNavigationItemView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASBottomNavigationItemViewImpl:(ASBottomNavigationItemViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt)

FOUNDATION_EXPORT void ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt_initWithASBottomNavigationItemViewImpl_(ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt *self, ASBottomNavigationItemViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt *new_ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt_initWithASBottomNavigationItemViewImpl_(ASBottomNavigationItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt *create_ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt_initWithASBottomNavigationItemViewImpl_(ASBottomNavigationItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationItemViewImpl_BottomNavigationItemViewExt)


#endif

#pragma pop_macro("INCLUDE_ALL_BottomNavigationItemViewImpl")
