//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\BottomNavigationViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BottomNavigationViewImpl")
#ifdef RESTRICT_BottomNavigationViewImpl
#define INCLUDE_ALL_BottomNavigationViewImpl 0
#else
#define INCLUDE_ALL_BottomNavigationViewImpl 1
#endif
#undef RESTRICT_BottomNavigationViewImpl

#if !defined (ASBottomNavigationViewImpl_) && (INCLUDE_ALL_BottomNavigationViewImpl || defined(INCLUDE_ASBottomNavigationViewImpl))
#define ASBottomNavigationViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASBottomNavigationViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationViewImpl)

inline NSString *ASBottomNavigationViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASBottomNavigationViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBottomNavigationViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBottomNavigationViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASBottomNavigationViewImpl_init(ASBottomNavigationViewImpl *self);

FOUNDATION_EXPORT ASBottomNavigationViewImpl *new_ASBottomNavigationViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationViewImpl *create_ASBottomNavigationViewImpl_init(void);

FOUNDATION_EXPORT void ASBottomNavigationViewImpl_initWithNSString_(ASBottomNavigationViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationViewImpl *new_ASBottomNavigationViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationViewImpl *create_ASBottomNavigationViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASBottomNavigationViewImpl_initWithNSString_withNSString_(ASBottomNavigationViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASBottomNavigationViewImpl *new_ASBottomNavigationViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationViewImpl *create_ASBottomNavigationViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationViewImpl)

@compatibility_alias ComAsheraNavigationviewBottomNavigationViewImpl ASBottomNavigationViewImpl;

#endif

#if !defined (ASBottomNavigationViewImpl_LabelVisibilityMode_) && (INCLUDE_ALL_BottomNavigationViewImpl || defined(INCLUDE_ASBottomNavigationViewImpl_LabelVisibilityMode))
#define ASBottomNavigationViewImpl_LabelVisibilityMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASBottomNavigationViewImpl_LabelVisibilityMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationViewImpl_LabelVisibilityMode)

FOUNDATION_EXPORT void ASBottomNavigationViewImpl_LabelVisibilityMode_init(ASBottomNavigationViewImpl_LabelVisibilityMode *self);

FOUNDATION_EXPORT ASBottomNavigationViewImpl_LabelVisibilityMode *new_ASBottomNavigationViewImpl_LabelVisibilityMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationViewImpl_LabelVisibilityMode *create_ASBottomNavigationViewImpl_LabelVisibilityMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationViewImpl_LabelVisibilityMode)

#endif

#if !defined (ASBottomNavigationViewImpl_BottomNavigationViewExt_) && (INCLUDE_ALL_BottomNavigationViewImpl || defined(INCLUDE_ASBottomNavigationViewImpl_BottomNavigationViewExt))
#define ASBottomNavigationViewImpl_BottomNavigationViewExt_

#define RESTRICT_BottomNavigationView 1
#define INCLUDE_ADXBottomNavigationView 1
#include "BottomNavigationView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASBottomNavigationViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASBottomNavigationViewImpl_BottomNavigationViewExt : ADXBottomNavigationView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASBottomNavigationViewImpl:(ASBottomNavigationViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationViewImpl_BottomNavigationViewExt)

FOUNDATION_EXPORT void ASBottomNavigationViewImpl_BottomNavigationViewExt_initWithASBottomNavigationViewImpl_(ASBottomNavigationViewImpl_BottomNavigationViewExt *self, ASBottomNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASBottomNavigationViewImpl_BottomNavigationViewExt *new_ASBottomNavigationViewImpl_BottomNavigationViewExt_initWithASBottomNavigationViewImpl_(ASBottomNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBottomNavigationViewImpl_BottomNavigationViewExt *create_ASBottomNavigationViewImpl_BottomNavigationViewExt_initWithASBottomNavigationViewImpl_(ASBottomNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationViewImpl_BottomNavigationViewExt)

#endif

#if !defined (ASBottomNavigationViewImpl_ValueSetter_) && (INCLUDE_ALL_BottomNavigationViewImpl || defined(INCLUDE_ASBottomNavigationViewImpl_ValueSetter))
#define ASBottomNavigationViewImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASBottomNavigationViewImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBottomNavigationViewImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASBottomNavigationViewImpl_ValueSetter)

#endif

#pragma pop_macro("INCLUDE_ALL_BottomNavigationViewImpl")
