//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationRailViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationRailViewImpl")
#ifdef RESTRICT_NavigationRailViewImpl
#define INCLUDE_ALL_NavigationRailViewImpl 0
#else
#define INCLUDE_ALL_NavigationRailViewImpl 1
#endif
#undef RESTRICT_NavigationRailViewImpl

#if !defined (ASNavigationRailViewImpl_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl))
#define ASNavigationRailViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNavigationRailViewImpl_NavigationRailViewBean;
@class ASNavigationRailViewImpl_NavigationRailViewCommandBuilder;
@class ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder;
@class ASNavigationRailViewImpl_NavigationRailViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationRailViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNavigationRailViewImpl_NavigationRailViewBean *)getBean;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNavigationRailViewImpl_NavigationRailViewParamsBean *)getParamsBean;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl)

inline NSString *ASNavigationRailViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationRailViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_init(ASNavigationRailViewImpl *self);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationRailViewImpl_initWithNSString_(ASNavigationRailViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationRailViewImpl_initWithNSString_withNSString_(ASNavigationRailViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationRailViewImpl ASNavigationRailViewImpl;

#endif

#if !defined (ASNavigationRailViewImpl_LabelVisibilityMode_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_LabelVisibilityMode))
#define ASNavigationRailViewImpl_LabelVisibilityMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASNavigationRailViewImpl_LabelVisibilityMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_LabelVisibilityMode)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_LabelVisibilityMode_init(ASNavigationRailViewImpl_LabelVisibilityMode *self);

FOUNDATION_EXPORT ASNavigationRailViewImpl_LabelVisibilityMode *new_ASNavigationRailViewImpl_LabelVisibilityMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_LabelVisibilityMode *create_ASNavigationRailViewImpl_LabelVisibilityMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_LabelVisibilityMode)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewExt_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewExt))
#define ASNavigationRailViewImpl_NavigationRailViewExt_

#define RESTRICT_NavigationRailView 1
#define INCLUDE_ADXNavigationRailView 1
#include "NavigationRailView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationRailViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationRailViewImpl_NavigationRailViewExt : ADXNavigationRailView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewExt)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewExt *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewExt *new_ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewExt *create_ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewExt)

#endif

#if !defined (ASNavigationRailViewImpl_ValueSetter_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_ValueSetter))
#define ASNavigationRailViewImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASNavigationRailViewImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_ValueSetter)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewCommandBuilder))
#define ASNavigationRailViewImpl_NavigationRailViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailViewImpl;

@interface ASNavigationRailViewImpl_NavigationRailViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                              withId:(id)arg1;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)endAnimator;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)invalidate;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)requestLayout;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)reset;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeAlphasWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeBackgroundColorsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeGravitiesWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeHorizontalOffsetsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeIsVisiblesWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeMaxCharacterCountsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeNumbersWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeTextAppearanceResourcesWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeTextColorsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBadgeVerticalOffsetsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setHeaderLayoutWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemBackgroundWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemIconSizeWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemIconTintWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemTextAppearanceActiveWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemTextAppearanceInactiveWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setItemTextColorWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLabelVisibilityModeWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMenuWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMenuGravityWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMenuItemIdsWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnItemReselectedWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnItemSelectedWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setSelectedItemIdWithNSString:(NSString *)value;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)startAnimator;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetAlpha;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetBackground;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetBackgroundTint;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetBottom;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetClickable;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetClipChildren;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetClipToPadding;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetContentDescription;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetEnabled;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetFocusable;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetForeground;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetForegroundGravity;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetForegroundTint;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetId;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAlpha;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsFocused;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsHidden;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosTag;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosTintColor;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetLayoutDirection;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetLayoutMode;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetLeft;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetLongClickable;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetMaxHeight;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetMaxWidth;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetMinHeight;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetMinWidth;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelDescPath;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelIdPath;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelParam;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingBottom;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingEnd;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingLeft;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingRight;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingStart;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetPaddingTop;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetRight;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetRotation;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetRotationX;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetRotationY;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetScaleX;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetScaleY;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetSelected;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTextAlignment;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTextDirection;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTop;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTransformPivotX;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTransformPivotY;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTranslationX;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTranslationY;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetTranslationZ;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetValidateForm;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)tryGetVisibility;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                    withId:(id)arg1;

- (ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewCommandBuilder)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewCommandBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *new_ASNavigationRailViewImpl_NavigationRailViewCommandBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewCommandBuilder *create_ASNavigationRailViewImpl_NavigationRailViewCommandBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewCommandBuilder)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewBean_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewBean))
#define ASNavigationRailViewImpl_NavigationRailViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailViewImpl;
@protocol ASIWidget;

@interface ASNavigationRailViewImpl_NavigationRailViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

- (void)setBadgeAlphasWithNSString:(NSString *)value;

- (void)setBadgeBackgroundColorsWithNSString:(NSString *)value;

- (void)setBadgeGravitiesWithNSString:(NSString *)value;

- (void)setBadgeHorizontalOffsetsWithNSString:(NSString *)value;

- (void)setBadgeIsVisiblesWithNSString:(NSString *)value;

- (void)setBadgeMaxCharacterCountsWithNSString:(NSString *)value;

- (void)setBadgeNumbersWithNSString:(NSString *)value;

- (void)setBadgeTextAppearanceResourcesWithNSString:(NSString *)value;

- (void)setBadgeTextColorsWithNSString:(NSString *)value;

- (void)setBadgeVerticalOffsetsWithNSString:(NSString *)value;

- (void)setHeaderLayoutWithNSString:(NSString *)value;

- (void)setItemBackgroundWithNSString:(NSString *)value;

- (void)setItemIconSizeWithNSString:(NSString *)value;

- (void)setItemIconTintWithNSString:(NSString *)value;

- (void)setItemTextAppearanceActiveWithNSString:(NSString *)value;

- (void)setItemTextAppearanceInactiveWithNSString:(NSString *)value;

- (void)setItemTextColorWithNSString:(NSString *)value;

- (void)setLabelVisibilityModeWithNSString:(NSString *)value;

- (void)setMenuWithNSString:(NSString *)value;

- (void)setMenuGravityWithNSString:(NSString *)value;

- (void)setMenuItemIdsWithNSString:(NSString *)value;

- (void)setOnItemReselectedWithNSString:(NSString *)value;

- (void)setOnItemSelectedWithNSString:(NSString *)value;

- (void)setSelectedItemIdWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewBean)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewBean *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewBean *new_ASNavigationRailViewImpl_NavigationRailViewBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewBean *create_ASNavigationRailViewImpl_NavigationRailViewBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewBean)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewParamsBean_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewParamsBean))
#define ASNavigationRailViewImpl_NavigationRailViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailViewImpl;

@interface ASNavigationRailViewImpl_NavigationRailViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewParamsBean)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewParamsBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewParamsBean *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewParamsBean *new_ASNavigationRailViewImpl_NavigationRailViewParamsBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewParamsBean *create_ASNavigationRailViewImpl_NavigationRailViewParamsBean_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewParamsBean)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder))
#define ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailViewImpl;

@interface ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)reset;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *new_ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder *create_ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationRailViewImpl")
