//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationViewPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationViewPlugin")
#ifdef RESTRICT_NavigationViewPlugin
#define INCLUDE_ALL_NavigationViewPlugin 0
#else
#define INCLUDE_ALL_NavigationViewPlugin 1
#endif
#undef RESTRICT_NavigationViewPlugin

#if !defined (ASNavigationViewPlugin_) && (INCLUDE_ALL_NavigationViewPlugin || defined(INCLUDE_ASNavigationViewPlugin))
#define ASNavigationViewPlugin_

@interface ASNavigationViewPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewPlugin)

FOUNDATION_EXPORT void ASNavigationViewPlugin_init(ASNavigationViewPlugin *self);

FOUNDATION_EXPORT ASNavigationViewPlugin *new_ASNavigationViewPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewPlugin *create_ASNavigationViewPlugin_init(void);

FOUNDATION_EXPORT void ASNavigationViewPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewPlugin)

@compatibility_alias ComAsheraNavigationviewNavigationViewPlugin ASNavigationViewPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_NavigationViewPlugin")
