//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationViewPlugin.java
//

#include "BaselineLayoutImpl.h"
#include "BottomNavigationItemViewImpl.h"
#include "BottomNavigationMenuViewImpl.h"
#include "BottomNavigationViewImpl.h"
#include "J2ObjC_source.h"
#include "NavigationRailItemViewImpl.h"
#include "NavigationRailMenuViewImpl.h"
#include "NavigationRailViewImpl.h"
#include "NavigationViewPlugin.h"
#include "WidgetFactory.h"


@implementation ASNavigationViewPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASNavigationViewPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASNavigationViewPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASNavigationViewPlugin = { "NavigationViewPlugin", "com.ashera.navigationview", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASNavigationViewPlugin;
}

@end

void ASNavigationViewPlugin_init(ASNavigationViewPlugin *self) {
  NSObject_init(self);
}

ASNavigationViewPlugin *new_ASNavigationViewPlugin_init() {
  J2OBJC_NEW_IMPL(ASNavigationViewPlugin, init)
}

ASNavigationViewPlugin *create_ASNavigationViewPlugin_init() {
  J2OBJC_CREATE_IMPL(ASNavigationViewPlugin, init)
}

void ASNavigationViewPlugin_initPlugin() {
  ASNavigationViewPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASBottomNavigationViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASBottomNavigationMenuViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASBottomNavigationItemViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASBaselineLayoutImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASNavigationRailViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASNavigationRailMenuViewImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASNavigationRailItemViewImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASNavigationViewPlugin)
