//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationRailItemViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationRailItemViewImpl")
#ifdef RESTRICT_NavigationRailItemViewImpl
#define INCLUDE_ALL_NavigationRailItemViewImpl 0
#else
#define INCLUDE_ALL_NavigationRailItemViewImpl 1
#endif
#undef RESTRICT_NavigationRailItemViewImpl

#if !defined (ASNavigationRailItemViewImpl_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl))
#define ASNavigationRailItemViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNavigationRailItemViewImpl_NavigationRailItemViewBean;
@class ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder;
@class ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder;
@class ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationRailItemViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewBean *)getBean;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean *)getParamsBean;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl)

inline NSString *ASNavigationRailItemViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailItemViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailItemViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationRailItemViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailItemViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailItemViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_init(ASNavigationRailItemViewImpl *self);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *new_ASNavigationRailItemViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *create_ASNavigationRailItemViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_initWithNSString_(ASNavigationRailItemViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *new_ASNavigationRailItemViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *create_ASNavigationRailItemViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_initWithNSString_withNSString_(ASNavigationRailItemViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *new_ASNavigationRailItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl *create_ASNavigationRailItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationRailItemViewImpl ASNavigationRailItemViewImpl;

#endif

#if !defined (ASNavigationRailItemViewImpl_NavigationRailItemViewExt_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl_NavigationRailItemViewExt))
#define ASNavigationRailItemViewImpl_NavigationRailItemViewExt_

#define RESTRICT_NavigationRailItemView 1
#define INCLUDE_ADXNavigationRailItemView 1
#include "NavigationRailItemView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationRailItemViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationRailItemViewImpl_NavigationRailItemViewExt : ADXNavigationRailItemView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationRailItemViewImpl:(ASNavigationRailItemViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl_NavigationRailItemViewExt)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_NavigationRailItemViewExt_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl_NavigationRailItemViewExt *self, ASNavigationRailItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewExt *new_ASNavigationRailItemViewImpl_NavigationRailItemViewExt_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewExt *create_ASNavigationRailItemViewImpl_NavigationRailItemViewExt_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl_NavigationRailItemViewExt)

#endif

#if !defined (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder))
#define ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailItemViewImpl;

@interface ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailItemViewImpl:(ASNavigationRailItemViewImpl *)outer$;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                      withId:(id)arg1;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)endAnimator;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)invalidate;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)requestLayout;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)reset;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)startAnimator;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetAlpha;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetBackground;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetBackgroundTint;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetBottom;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetClickable;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetClipChildren;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetClipToPadding;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetContentDescription;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetEnabled;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetFocusable;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetForeground;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetForegroundGravity;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetForegroundTint;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetId;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAlpha;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsFocused;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsHidden;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosTag;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosTintColor;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetLayoutDirection;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetLayoutMode;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetLeft;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetLongClickable;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetMaxHeight;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetMaxWidth;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetMinHeight;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetMinWidth;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelDescPath;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelIdPath;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelParam;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingBottom;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingEnd;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingLeft;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingRight;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingStart;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetPaddingTop;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetRight;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetRotation;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetRotationX;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetRotationY;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetScaleX;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetScaleY;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetSelected;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTextAlignment;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTextDirection;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTop;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTransformPivotX;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTransformPivotY;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTranslationX;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTranslationY;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetTranslationZ;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetValidateForm;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)tryGetVisibility;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                            withId:(id)arg1;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *self, ASNavigationRailItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *new_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder *create_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandBuilder)

#endif

#if !defined (ASNavigationRailItemViewImpl_NavigationRailItemViewBean_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl_NavigationRailItemViewBean))
#define ASNavigationRailItemViewImpl_NavigationRailItemViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailItemViewImpl;
@protocol ASIWidget;

@interface ASNavigationRailItemViewImpl_NavigationRailItemViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNavigationRailItemViewImpl:(ASNavigationRailItemViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl_NavigationRailItemViewBean)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_NavigationRailItemViewBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl_NavigationRailItemViewBean *self, ASNavigationRailItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewBean *new_ASNavigationRailItemViewImpl_NavigationRailItemViewBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewBean *create_ASNavigationRailItemViewImpl_NavigationRailItemViewBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl_NavigationRailItemViewBean)

#endif

#if !defined (ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean))
#define ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailItemViewImpl;

@interface ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNavigationRailItemViewImpl:(ASNavigationRailItemViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean *self, ASNavigationRailItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean *new_ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean *create_ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl_NavigationRailItemViewParamsBean)

#endif

#if !defined (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder_) && (INCLUDE_ALL_NavigationRailItemViewImpl || defined(INCLUDE_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder))
#define ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailItemViewImpl;

@interface ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailItemViewImpl:(ASNavigationRailItemViewImpl *)outer$;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)reset;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *self, ASNavigationRailItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *new_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder *create_ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder_initWithASNavigationRailItemViewImpl_(ASNavigationRailItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailItemViewImpl_NavigationRailItemViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationRailItemViewImpl")
