//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationViewImpl")
#ifdef RESTRICT_NavigationViewImpl
#define INCLUDE_ALL_NavigationViewImpl 0
#else
#define INCLUDE_ALL_NavigationViewImpl 1
#endif
#undef RESTRICT_NavigationViewImpl

#if !defined (ASNavigationViewImpl_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl))
#define ASNavigationViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNavigationViewImpl_NavigationViewBean;
@class ASNavigationViewImpl_NavigationViewCommandBuilder;
@class ASNavigationViewImpl_NavigationViewCommandParamsBuilder;
@class ASNavigationViewImpl_NavigationViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@class IOSObjectArray;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNavigationViewImpl_NavigationViewBean *)getBean;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNavigationViewImpl_NavigationViewParamsBean *)getParamsBean;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (id)invokeMethodWithNSString:(NSString *)methodName
             withNSObjectArray:(IOSObjectArray *)args;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl)

inline NSString *ASNavigationViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationViewImpl_init(ASNavigationViewImpl *self);

FOUNDATION_EXPORT ASNavigationViewImpl *new_ASNavigationViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl *create_ASNavigationViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationViewImpl_initWithNSString_(ASNavigationViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationViewImpl *new_ASNavigationViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl *create_ASNavigationViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationViewImpl_initWithNSString_withNSString_(ASNavigationViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationViewImpl *new_ASNavigationViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl *create_ASNavigationViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationViewImpl ASNavigationViewImpl;

#endif

#if !defined (ASNavigationViewImpl_NavigationViewExt_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl_NavigationViewExt))
#define ASNavigationViewImpl_NavigationViewExt_

#define RESTRICT_NavigationView 1
#define INCLUDE_ADXNavigationView 1
#include "NavigationView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationViewImpl_NavigationViewExt : ADXNavigationView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationViewImpl:(ASNavigationViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl_NavigationViewExt)

FOUNDATION_EXPORT void ASNavigationViewImpl_NavigationViewExt_initWithASNavigationViewImpl_(ASNavigationViewImpl_NavigationViewExt *self, ASNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewExt *new_ASNavigationViewImpl_NavigationViewExt_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewExt *create_ASNavigationViewImpl_NavigationViewExt_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl_NavigationViewExt)

#endif

#if !defined (ASNavigationViewImpl_NavigationViewCommandBuilder_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl_NavigationViewCommandBuilder))
#define ASNavigationViewImpl_NavigationViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationViewImpl;

@interface ASNavigationViewImpl_NavigationViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNavigationViewImpl:(ASNavigationViewImpl *)outer$;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                      withId:(id)arg1;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)endAnimator;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getItemBackground;

- (id)getItemHorizontalPadding;

- (id)getItemIconPadding;

- (id)getItemIconTint;

- (id)getItemMaxLines;

- (id)getItemTextColor;

- (id)getItemVerticalPadding;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)invalidate;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)requestLayout;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)reset;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setDividerInsetEndWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setDividerInsetStartWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setHeaderLayoutWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemBackgroundWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemHorizontalPaddingWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemIconPaddingWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemIconSizeWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemIconTintWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemMaxLinesWithInt:(jint)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemTextAppearanceWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemTextColorWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setItemVerticalPaddingWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setMenuWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnItemSelectedWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setSubheaderInsetEndWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setSubheaderInsetStartWithNSString:(NSString *)value;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)startAnimator;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetAlpha;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetBackground;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetBackgroundTint;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetBottom;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetClickable;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetClipChildren;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetClipToPadding;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetContentDescription;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetEnabled;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetFocusable;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetForeground;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetForegroundGravity;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetForegroundTint;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetId;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAlpha;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsFocused;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsHidden;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosTag;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosTintColor;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemBackground;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemHorizontalPadding;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemIconPadding;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemIconTint;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemMaxLines;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemTextColor;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetItemVerticalPadding;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetLayoutDirection;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetLayoutMode;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetLeft;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetLongClickable;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetMaxHeight;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetMaxWidth;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetMinHeight;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetMinWidth;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelDescPath;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelIdPath;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelParam;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingBottom;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingEnd;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingLeft;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingRight;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingStart;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetPaddingTop;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetRight;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetRotation;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetRotationX;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetRotationY;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetScaleX;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetScaleY;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetSelected;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTextAlignment;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTextDirection;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTop;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTransformPivotX;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTransformPivotY;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTranslationX;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTranslationY;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetTranslationZ;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetValidateForm;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)tryGetVisibility;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                            withId:(id)arg1;

- (ASNavigationViewImpl_NavigationViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl_NavigationViewCommandBuilder)

FOUNDATION_EXPORT void ASNavigationViewImpl_NavigationViewCommandBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl_NavigationViewCommandBuilder *self, ASNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewCommandBuilder *new_ASNavigationViewImpl_NavigationViewCommandBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewCommandBuilder *create_ASNavigationViewImpl_NavigationViewCommandBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl_NavigationViewCommandBuilder)

#endif

#if !defined (ASNavigationViewImpl_NavigationViewBean_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl_NavigationViewBean))
#define ASNavigationViewImpl_NavigationViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNavigationViewImpl;
@protocol ASIWidget;

@interface ASNavigationViewImpl_NavigationViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNavigationViewImpl:(ASNavigationViewImpl *)outer$;

- (id)getItemBackground;

- (id)getItemHorizontalPadding;

- (id)getItemIconPadding;

- (id)getItemIconTint;

- (id)getItemMaxLines;

- (id)getItemTextColor;

- (id)getItemVerticalPadding;

- (void)setDividerInsetEndWithNSString:(NSString *)value;

- (void)setDividerInsetStartWithNSString:(NSString *)value;

- (void)setHeaderLayoutWithNSString:(NSString *)value;

- (void)setItemBackgroundWithNSString:(NSString *)value;

- (void)setItemHorizontalPaddingWithNSString:(NSString *)value;

- (void)setItemIconPaddingWithNSString:(NSString *)value;

- (void)setItemIconSizeWithNSString:(NSString *)value;

- (void)setItemIconTintWithNSString:(NSString *)value;

- (void)setItemMaxLinesWithInt:(jint)value;

- (void)setItemTextAppearanceWithNSString:(NSString *)value;

- (void)setItemTextColorWithNSString:(NSString *)value;

- (void)setItemVerticalPaddingWithNSString:(NSString *)value;

- (void)setMenuWithNSString:(NSString *)value;

- (void)setOnItemSelectedWithNSString:(NSString *)value;

- (void)setSubheaderInsetEndWithNSString:(NSString *)value;

- (void)setSubheaderInsetStartWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl_NavigationViewBean)

FOUNDATION_EXPORT void ASNavigationViewImpl_NavigationViewBean_initWithASNavigationViewImpl_(ASNavigationViewImpl_NavigationViewBean *self, ASNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewBean *new_ASNavigationViewImpl_NavigationViewBean_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewBean *create_ASNavigationViewImpl_NavigationViewBean_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl_NavigationViewBean)

#endif

#if !defined (ASNavigationViewImpl_NavigationViewParamsBean_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl_NavigationViewParamsBean))
#define ASNavigationViewImpl_NavigationViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNavigationViewImpl;

@interface ASNavigationViewImpl_NavigationViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNavigationViewImpl:(ASNavigationViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl_NavigationViewParamsBean)

FOUNDATION_EXPORT void ASNavigationViewImpl_NavigationViewParamsBean_initWithASNavigationViewImpl_(ASNavigationViewImpl_NavigationViewParamsBean *self, ASNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewParamsBean *new_ASNavigationViewImpl_NavigationViewParamsBean_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewParamsBean *create_ASNavigationViewImpl_NavigationViewParamsBean_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl_NavigationViewParamsBean)

#endif

#if !defined (ASNavigationViewImpl_NavigationViewCommandParamsBuilder_) && (INCLUDE_ALL_NavigationViewImpl || defined(INCLUDE_ASNavigationViewImpl_NavigationViewCommandParamsBuilder))
#define ASNavigationViewImpl_NavigationViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationViewImpl;

@interface ASNavigationViewImpl_NavigationViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNavigationViewImpl:(ASNavigationViewImpl *)outer$;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)reset;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNavigationViewImpl_NavigationViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationViewImpl_NavigationViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNavigationViewImpl_NavigationViewCommandParamsBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl_NavigationViewCommandParamsBuilder *self, ASNavigationViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewCommandParamsBuilder *new_ASNavigationViewImpl_NavigationViewCommandParamsBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationViewImpl_NavigationViewCommandParamsBuilder *create_ASNavigationViewImpl_NavigationViewCommandParamsBuilder_initWithASNavigationViewImpl_(ASNavigationViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationViewImpl_NavigationViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationViewImpl")
