//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationRailViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationRailViewImpl")
#ifdef RESTRICT_NavigationRailViewImpl
#define INCLUDE_ALL_NavigationRailViewImpl 0
#else
#define INCLUDE_ALL_NavigationRailViewImpl 1
#endif
#undef RESTRICT_NavigationRailViewImpl

#if !defined (ASNavigationRailViewImpl_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl))
#define ASNavigationRailViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationRailViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl)

inline NSString *ASNavigationRailViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationRailViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_init(ASNavigationRailViewImpl *self);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationRailViewImpl_initWithNSString_(ASNavigationRailViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationRailViewImpl_initWithNSString_withNSString_(ASNavigationRailViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailViewImpl *new_ASNavigationRailViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl *create_ASNavigationRailViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationRailViewImpl ASNavigationRailViewImpl;

#endif

#if !defined (ASNavigationRailViewImpl_LabelVisibilityMode_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_LabelVisibilityMode))
#define ASNavigationRailViewImpl_LabelVisibilityMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASNavigationRailViewImpl_LabelVisibilityMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_LabelVisibilityMode)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_LabelVisibilityMode_init(ASNavigationRailViewImpl_LabelVisibilityMode *self);

FOUNDATION_EXPORT ASNavigationRailViewImpl_LabelVisibilityMode *new_ASNavigationRailViewImpl_LabelVisibilityMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_LabelVisibilityMode *create_ASNavigationRailViewImpl_LabelVisibilityMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_LabelVisibilityMode)

#endif

#if !defined (ASNavigationRailViewImpl_NavigationRailViewExt_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_NavigationRailViewExt))
#define ASNavigationRailViewImpl_NavigationRailViewExt_

#define RESTRICT_NavigationRailView 1
#define INCLUDE_ADXNavigationRailView 1
#include "NavigationRailView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationRailViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationRailViewImpl_NavigationRailViewExt : ADXNavigationRailView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationRailViewImpl:(ASNavigationRailViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_NavigationRailViewExt)

FOUNDATION_EXPORT void ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl_NavigationRailViewExt *self, ASNavigationRailViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewExt *new_ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailViewImpl_NavigationRailViewExt *create_ASNavigationRailViewImpl_NavigationRailViewExt_initWithASNavigationRailViewImpl_(ASNavigationRailViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_NavigationRailViewExt)

#endif

#if !defined (ASNavigationRailViewImpl_ValueSetter_) && (INCLUDE_ALL_NavigationRailViewImpl || defined(INCLUDE_ASNavigationRailViewImpl_ValueSetter))
#define ASNavigationRailViewImpl_ValueSetter_

@class ADXBadgeDrawable;

@protocol ASNavigationRailViewImpl_ValueSetter < JavaObject >

- (void)setValueOnBadgeDrawableWithADXBadgeDrawable:(ADXBadgeDrawable *)badgeDrawable
                                             withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailViewImpl_ValueSetter)

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailViewImpl_ValueSetter)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationRailViewImpl")
