//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationRailMenuViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationRailMenuViewImpl")
#ifdef RESTRICT_NavigationRailMenuViewImpl
#define INCLUDE_ALL_NavigationRailMenuViewImpl 0
#else
#define INCLUDE_ALL_NavigationRailMenuViewImpl 1
#endif
#undef RESTRICT_NavigationRailMenuViewImpl

#if !defined (ASNavigationRailMenuViewImpl_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl))
#define ASNavigationRailMenuViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationRailMenuViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl)

inline NSString *ASNavigationRailMenuViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailMenuViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailMenuViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationRailMenuViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailMenuViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailMenuViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_init(ASNavigationRailMenuViewImpl *self);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_initWithNSString_(ASNavigationRailMenuViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(ASNavigationRailMenuViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationRailMenuViewImpl ASNavigationRailMenuViewImpl;


#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_

#define RESTRICT_NavigationRailMenuView 1
#define INCLUDE_ADXNavigationRailMenuView 1
#include "NavigationRailMenuView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationRailMenuViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt : ADXNavigationRailMenuView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt)


#endif

#pragma pop_macro("INCLUDE_ALL_NavigationRailMenuViewImpl")
