//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationMenuItemViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationMenuItemViewImpl")
#ifdef RESTRICT_NavigationMenuItemViewImpl
#define INCLUDE_ALL_NavigationMenuItemViewImpl 0
#else
#define INCLUDE_ALL_NavigationMenuItemViewImpl 1
#endif
#undef RESTRICT_NavigationMenuItemViewImpl

#if !defined (ASNavigationMenuItemViewImpl_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl))
#define ASNavigationMenuItemViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean;
@class ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder;
@class ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder;
@class ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationMenuItemViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean *)getBean;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean *)getParamsBean;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl)

inline NSString *ASNavigationMenuItemViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationMenuItemViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationMenuItemViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationMenuItemViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationMenuItemViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationMenuItemViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_init(ASNavigationMenuItemViewImpl *self);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *new_ASNavigationMenuItemViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *create_ASNavigationMenuItemViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_initWithNSString_(ASNavigationMenuItemViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *new_ASNavigationMenuItemViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *create_ASNavigationMenuItemViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_initWithNSString_withNSString_(ASNavigationMenuItemViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *new_ASNavigationMenuItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl *create_ASNavigationMenuItemViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationMenuItemViewImpl ASNavigationMenuItemViewImpl;

#endif

#if !defined (ASNavigationMenuItemViewImpl_Divider_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_Divider))
#define ASNavigationMenuItemViewImpl_Divider_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASNavigationMenuItemViewImpl_Divider : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_Divider)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_Divider_init(ASNavigationMenuItemViewImpl_Divider *self);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_Divider *new_ASNavigationMenuItemViewImpl_Divider_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_Divider *create_ASNavigationMenuItemViewImpl_Divider_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_Divider)

#endif

#if !defined (ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt))
#define ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt_

#define RESTRICT_NavigationMenuItemView 1
#define INCLUDE_ADXNavigationMenuItemView 1
#include "NavigationMenuItemView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationMenuItemViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt : ADXNavigationMenuItemView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationMenuItemViewImpl:(ASNavigationMenuItemViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt *self, ASNavigationMenuItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt *new_ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt *create_ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_NavigationMenuItemViewExt)

#endif

#if !defined (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder))
#define ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationMenuItemViewImpl;

@interface ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNavigationMenuItemViewImpl:(ASNavigationMenuItemViewImpl *)outer$;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                      withId:(id)arg1;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)endAnimator;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getBaselineAlignedChildIndex;

- (id)getDivider;

- (id)getDividerPadding;

- (id)getGravity;

- (id)getShowDividers;

- (id)getWeightSum;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)invalidate;

- (id)isBaselineAligned;

- (id)isMeasureWithLargestChild;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)requestLayout;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)reset;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBaselineAlignedWithBoolean:(jboolean)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBaselineAlignedChildIndexWithInt:(jint)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setDividerWithNSString:(NSString *)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setDividerPaddingWithNSString:(NSString *)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setGravityWithNSString:(NSString *)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setMeasureWithLargestChildWithBoolean:(jboolean)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setShowDividersWithNSString:(NSString *)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setWeightSumWithFloat:(jfloat)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)startAnimator;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetAlpha;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBackground;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBackgroundTint;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBaselineAligned;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBaselineAlignedChildIndex;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetBottom;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetClickable;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetClipChildren;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetClipToPadding;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetContentDescription;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetDivider;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetDividerPadding;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetEnabled;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetFocusable;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetForeground;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetForegroundGravity;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetForegroundTint;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetGravity;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetId;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAlpha;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsFocused;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsHidden;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosTag;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosTintColor;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetLayoutDirection;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetLayoutMode;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetLeft;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetLongClickable;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetMaxHeight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetMaxWidth;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetMeasureWithLargestChild;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetMinHeight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetMinWidth;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelDescPath;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelIdPath;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelParam;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingBottom;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingEnd;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingLeft;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingRight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingStart;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetPaddingTop;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetRight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetRotation;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetRotationX;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetRotationY;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetScaleX;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetScaleY;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetSelected;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetShowDividers;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTextAlignment;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTextDirection;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTop;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTransformPivotX;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTransformPivotY;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTranslationX;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTranslationY;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetTranslationZ;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetValidateForm;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetVisibility;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)tryGetWeightSum;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                            withId:(id)arg1;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *self, ASNavigationMenuItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *new_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder *create_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandBuilder)

#endif

#if !defined (ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean))
#define ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNavigationMenuItemViewImpl;
@protocol ASIWidget;

@interface ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNavigationMenuItemViewImpl:(ASNavigationMenuItemViewImpl *)outer$;

- (id)getBaselineAlignedChildIndex;

- (id)getDivider;

- (id)getDividerPadding;

- (id)getGravity;

- (id)getShowDividers;

- (id)getWeightSum;

- (id)isBaselineAligned;

- (id)isMeasureWithLargestChild;

- (void)setBaselineAlignedWithBoolean:(jboolean)value;

- (void)setBaselineAlignedChildIndexWithInt:(jint)value;

- (void)setDividerWithNSString:(NSString *)value;

- (void)setDividerPaddingWithNSString:(NSString *)value;

- (void)setGravityWithNSString:(NSString *)value;

- (void)setMeasureWithLargestChildWithBoolean:(jboolean)value;

- (void)setShowDividersWithNSString:(NSString *)value;

- (void)setWeightSumWithFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean *self, ASNavigationMenuItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean *new_ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean *create_ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_NavigationMenuItemViewBean)

#endif

#if !defined (ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean))
#define ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNavigationMenuItemViewImpl;
@protocol ASIWidget;

@interface ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNavigationMenuItemViewImpl:(ASNavigationMenuItemViewImpl *)outer$;

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutWeightWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

- (void)setLayoutWeightWithASIWidget:(id<ASIWidget>)w
                           withFloat:(jfloat)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean *self, ASNavigationMenuItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean *new_ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean *create_ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_NavigationMenuItemViewParamsBean)

#endif

#if !defined (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder_) && (INCLUDE_ALL_NavigationMenuItemViewImpl || defined(INCLUDE_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder))
#define ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationMenuItemViewImpl;

@interface ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNavigationMenuItemViewImpl:(ASNavigationMenuItemViewImpl *)outer$;

- (id)getLayoutGravity;

- (id)getLayoutWeight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)reset;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)setLayoutWeightWithFloat:(jfloat)value;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutGravity;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutMarginTop;

- (ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *)tryGetLayoutWeight;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *self, ASNavigationMenuItemViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *new_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder *create_ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder_initWithASNavigationMenuItemViewImpl_(ASNavigationMenuItemViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationMenuItemViewImpl_NavigationMenuItemViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationMenuItemViewImpl")
