//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSNavigationViewPlugin\src\main\java\com\ashera\navigationview\NavigationRailMenuViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_NavigationRailMenuViewImpl")
#ifdef RESTRICT_NavigationRailMenuViewImpl
#define INCLUDE_ALL_NavigationRailMenuViewImpl 0
#else
#define INCLUDE_ALL_NavigationRailMenuViewImpl 1
#endif
#undef RESTRICT_NavigationRailMenuViewImpl

#if !defined (ASNavigationRailMenuViewImpl_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl))
#define ASNavigationRailMenuViewImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean;
@class ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder;
@class ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder;
@class ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASNavigationRailMenuViewImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean *)getBean;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean *)getParamsBean;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreate;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl)

inline NSString *ASNavigationRailMenuViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailMenuViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailMenuViewImpl, LOCAL_NAME, NSString *)

inline NSString *ASNavigationRailMenuViewImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASNavigationRailMenuViewImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASNavigationRailMenuViewImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_init(ASNavigationRailMenuViewImpl *self);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_init(void);

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_initWithNSString_(ASNavigationRailMenuViewImpl *self, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(ASNavigationRailMenuViewImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *new_ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl *create_ASNavigationRailMenuViewImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl)

@compatibility_alias ComAsheraNavigationviewNavigationRailMenuViewImpl ASNavigationRailMenuViewImpl;

#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_

#define RESTRICT_NavigationRailMenuView 1
#define INCLUDE_ADXNavigationRailMenuView 1
#include "NavigationRailMenuView.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASNavigationRailMenuViewImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt : ADXNavigationRailMenuView < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewExt)

#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailMenuViewImpl;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                                      withId:(id)arg1;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)addModelWithId:(id)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)animatorXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)endAnimator;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)invalidate;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)requestLayout;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)reset;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAnimateLayoutChangesWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAnimateParentHierarchyWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setElevationWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLayoutTransitionDurationWithInt:(jint)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLayoutTransitionWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnAnimationCancelWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnAnimationEndWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnAnimationRepeatWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnAnimationStartWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setRightWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTopWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)startAnimator;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetAddStatesFromChildren;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetAlpha;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetBackground;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetBackgroundTint;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetBottom;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetClickable;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetClipChildren;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetClipToPadding;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetContentDescription;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetDuplicateParentState;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetEnabled;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetFocusable;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetForeground;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetForegroundGravity;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetForegroundTint;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetForegroundTintMode;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetId;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAlpha;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsFocused;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsHidden;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsOpaque;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosTag;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosTintColor;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetKeepScreenOn;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetLayoutDirection;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetLayoutMode;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetLeft;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetLongClickable;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetMaxHeight;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetMaxWidth;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetMinHeight;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetMinWidth;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelDescPath;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelIdPath;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelParam;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelPojoToUi;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelSyncEvents;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetModelUiToPojo;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingBottom;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingEnd;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingLeft;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingRight;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingStart;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetPaddingTop;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetRight;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetRotation;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetRotationX;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetRotationY;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetScaleX;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetScaleY;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetSelected;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTextAlignment;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTextDirection;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTop;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTransformPivotX;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTransformPivotY;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTranslationX;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTranslationY;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetTranslationZ;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetValidateForm;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)tryGetVisibility;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                            withId:(id)arg1;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandBuilder)

#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailMenuViewImpl;
@protocol ASIWidget;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewBean)

#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASNavigationRailMenuViewImpl;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewParamsBean)

#endif

#if !defined (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder_) && (INCLUDE_ALL_NavigationRailMenuViewImpl || defined(INCLUDE_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder))
#define ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASNavigationRailMenuViewImpl;

@interface ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASNavigationRailMenuViewImpl:(ASNavigationRailMenuViewImpl *)outer$;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)reset;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder)

FOUNDATION_EXPORT void ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *self, ASNavigationRailMenuViewImpl *outer$);

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *new_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder *create_ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder_initWithASNavigationRailMenuViewImpl_(ASNavigationRailMenuViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASNavigationRailMenuViewImpl_NavigationRailMenuViewCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_NavigationRailMenuViewImpl")
